/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Design;

import Koneksi.Koneksi;
import DAO.*;
import Model.*;
import Service.*;
import TableModel.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class Form_BarangMasuk extends javax.swing.JPanel {

    private Connection conn;

    private Service_BarangMasuk servis_masuk = new DAO_BarangMasuk();
    private Service_DetBarangMasuk servis_detmasuk = new DAO_DetBarangMasuk();

    private TblMod_BarangMasuk tblModel_masuk = new TblMod_BarangMasuk();
    private TblMod_DetBarangMasuk tblModel_detmasuk = new TblMod_DetBarangMasuk();

    private Service_SemBarangMasuk servis = new DAO_SemBarangMasuk();
    private TblMod_SemBarangMasuk tblModel = new TblMod_SemBarangMasuk();

//    private Service_Laporan servis_lap = new DAO_Laporan();
    public Form_BarangMasuk(String Id) {
        initComponents();
        bt_perbaruisem.setEnabled(false);
        bt_hapusem.setEnabled(false);
        conn = Koneksi.getConnection();

        //Pengaturan Tabel BarangMasuk
        tbl_BarangMasuk.setModel(tblModel_masuk);

        tbl_BarangMasuk.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbl_BarangMasuk.getTableHeader().setOpaque(false);
        tbl_BarangMasuk.getTableHeader().setBackground(new Color(0, 48, 88));
        tbl_BarangMasuk.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl_BarangMasuk.setRowHeight(27);

        //Pengaturan Tabel Sementara
        tbl_sementara.setModel(tblModel);
        tbl_sementara.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbl_sementara.getTableHeader().setOpaque(false);
        tbl_sementara.getTableHeader().setBackground(new Color(0, 48, 88));
        tbl_sementara.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl_sementara.setRowHeight(27);

        //Pengaturan Tabel Detail BarangMasuk Barang
        tbl_detail.setModel(tblModel);
        tbl_detail.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbl_detail.getTableHeader().setOpaque(false);
        tbl_detail.getTableHeader().setBackground(new Color(0, 48, 88));
        tbl_detail.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl_detail.setRowHeight(27);

        t_jumbar.setEditable(false);
        lb_id.setText(Id);
        //setLocationRelativeTo(null);
        tbl_sementara.setModel(tblModel);
        tbl_BarangMasuk.setModel(tblModel_masuk);
        tbl_detail.setModel(tblModel_detmasuk);
        loadData();
        loadDataSementara();
        pn_detail.setVisible(false);
        resetForm();
        nonAktif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarangMasuk = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_BarangMasuk = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        t_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_detail = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        tambahBarangMasuk = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sementara = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        t_iddis = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        t_namadis = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        t_kodbar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_nambar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t_harbar = new javax.swing.JTextField();
        t_jumbar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t_subtotal = new javax.swing.JTextField();
        t_satuan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_tanggal = new javax.swing.JTextField();
        bt_perbaruisem = new javax.swing.JButton();
        bt_hapusem = new javax.swing.JButton();
        lb_tobar = new javax.swing.JLabel();
        bt_tambahdata1 = new javax.swing.JButton();
        bt_hapusdata2 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarangMasuk.setBackground(new java.awt.Color(255, 255, 255));
        dataBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataBarangMasukMouseClicked(evt);
            }
        });

        tbl_BarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_BarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BarangMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_BarangMasuk);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Barang Masuk");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/cari.png"))); // NOI18N

        lb_id.setForeground(new java.awt.Color(255, 255, 255));
        lb_id.setText("lb_id");

        pn_detail.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 48, 88));
        jLabel4.setText("Detail Barang Masuk");

        jSeparator3.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_detail);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jSeparator3)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_tambahdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata.setText("TAMBAH");
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
        });
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangMasukLayout = new javax.swing.GroupLayout(dataBarangMasuk);
        dataBarangMasuk.setLayout(dataBarangMasukLayout);
        dataBarangMasukLayout.setHorizontalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pn_detail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataBarangMasukLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dataBarangMasukLayout.setVerticalGroup(
            dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_cari)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(dataBarangMasuk, "card2");

        tambahBarangMasuk.setBackground(new java.awt.Color(255, 255, 255));

        tbl_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sementaraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_sementara);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 116, 130)));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("ID Distributor");

        t_iddis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("Nama Distributor");

        t_namadis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        t_namadis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namadisActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Distributor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(t_iddis, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addComponent(t_namadis))
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_namadis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_iddis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 116, 130)));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Kode Barang");

        t_kodbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("Nama Barang");

        t_nambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Harga");

        t_harbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        t_jumbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        t_jumbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_jumbarActionPerformed(evt);
            }
        });
        t_jumbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_jumbarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_jumbarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_jumbarKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("Jumlah");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Subtotal");

        t_subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        t_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_subtotalActionPerformed(evt);
            }
        });

        t_satuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("Satuan");

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Barang");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel22)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(t_kodbar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(t_nambar)
                    .addComponent(t_satuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18)
                    .addComponent(t_harbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addComponent(t_jumbar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(t_subtotal))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_kodbar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_harbar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nambar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_jumbar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Barang Masuk");

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Total Masuk");

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Masuk");

        t_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_no.setBorder(null);
        t_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_noActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");

        t_tanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_tanggal.setBorder(null);
        t_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(t_no, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bt_perbaruisem.setBackground(new java.awt.Color(0, 0, 102));
        bt_perbaruisem.setForeground(new java.awt.Color(255, 255, 255));
        bt_perbaruisem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_perbaruisem.setText("PERBARUI");
        bt_perbaruisem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_perbaruisemMouseClicked(evt);
            }
        });
        bt_perbaruisem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_perbaruisemActionPerformed(evt);
            }
        });

        bt_hapusem.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusem.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/hapus.png"))); // NOI18N
        bt_hapusem.setText("HAPUS");
        bt_hapusem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusemMouseClicked(evt);
            }
        });
        bt_hapusem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusemActionPerformed(evt);
            }
        });

        lb_tobar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lb_tobar.setForeground(new java.awt.Color(0, 0, 102));
        lb_tobar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_tobar.setText("Total");
        lb_tobar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bt_tambahdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata1.setText("TAMBAH");
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
        });
        bt_tambahdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdata1ActionPerformed(evt);
            }
        });

        bt_hapusdata2.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata2.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_hapusdata2.setText("BATAL");
        bt_hapusdata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata2MouseClicked(evt);
            }
        });
        bt_hapusdata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdata2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahBarangMasukLayout = new javax.swing.GroupLayout(tambahBarangMasuk);
        tambahBarangMasuk.setLayout(tambahBarangMasukLayout);
        tambahBarangMasukLayout.setHorizontalGroup(
            tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_hapusdata2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(lb_tobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(bt_perbaruisem, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(bt_hapusem, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        tambahBarangMasukLayout.setVerticalGroup(
            tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(lb_tobar))
                    .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_hapusdata2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambahBarangMasukLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tambahBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_perbaruisem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_hapusem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahBarangMasuk, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_BarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_BarangMasukMouseClicked
        int row = tbl_BarangMasuk.getSelectedRow();
        String id = tbl_BarangMasuk.getValueAt(row, 0).toString();
        pn_detail.setVisible(true);
        List<Model_DetBarangMasuk> list = servis_detmasuk.getData(id);
        tblModel_detmasuk.setData(list);
    }//GEN-LAST:event_tbl_BarangMasukMouseClicked

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void dataBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBarangMasukMouseClicked
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_dataBarangMasukMouseClicked

    private void tbl_sementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sementaraMouseClicked
        int row = tbl_sementara.getSelectedRow();

        t_kodbar.setEditable(false);
        t_nambar.setEditable(false);
        t_satuan.setEditable(false);
        t_harbar.setEditable(false);
        t_subtotal.setEditable(false);

        t_kodbar.setText(tbl_sementara.getModel().getValueAt(row, 0).toString());
        t_nambar.setText(tbl_sementara.getModel().getValueAt(row, 1).toString());
        t_satuan.setText(tbl_sementara.getModel().getValueAt(row, 2).toString());
        t_harbar.setText(tbl_sementara.getModel().getValueAt(row, 3).toString());
        t_jumbar.setText(tbl_sementara.getModel().getValueAt(row, 4).toString());
        Integer x = Integer.parseInt(t_harbar.getText()) * Integer.parseInt(t_jumbar.getText());
        t_subtotal.setText(x.toString());

        t_jumbar.setEditable(true);

        bt_perbaruisem.setEnabled(true);
        bt_hapusem.setEnabled(true);
//        t_satuan.setVisible(false);
//        jLabel22.setVisible(false);
    }//GEN-LAST:event_tbl_sementaraMouseClicked

    private void t_namadisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namadisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namadisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean closable = true;
        Data_Distributor datdis = new Data_Distributor(null, closable);
        datdis.setVisible(true);

        t_iddis.setText(datdis.dst.getId_distributor());
        t_namadis.setText(datdis.dst.getNama_distributor());

        t_kodbar.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_jumbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_jumbarActionPerformed
        if (t_jumbar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah masih kosong!");
        } else if (t_jumbar.getText().toString().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jumlah tidak boleh 0!");
        } else {
            String kode = t_kodbar.getText();
            String nama = t_nambar.getText();
            String satuan = t_satuan.getText();

            bt_perbaruisem.setEnabled(false);

            int jumlah;
            Long harga, subtotal;
            harga = Long.valueOf(t_harbar.getText());
            jumlah = Integer.parseInt(t_jumbar.getText());
            subtotal = harga * jumlah;
            t_subtotal.setText(Long.toString(subtotal));

            Model_Barang brg = new Model_Barang();
            Model_DetBarangMasuk det_masuk = new Model_DetBarangMasuk();

//        Model_BarangMasuk masuk = new Model_BarangMasuk();
            Model_SemBarangMasuk smt = new Model_SemBarangMasuk();

            brg.setKode_barang(kode);
            brg.setNama_barang(nama);
            brg.setSatuan(satuan);
            brg.setHarga(harga);

            det_masuk.setJml_masuk(jumlah);
            det_masuk.setSubtotal_masuk(subtotal);

            smt.setMdl_barang(brg);
            smt.setMdl_detmasuk(det_masuk);

            //sumSubTotal();
            if (JOptionPane.showConfirmDialog(this, "Mau Tambah Barang?",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (t_iddis.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Distributor tidak boleh kosong!");
                } else {

                    if (servis.cekIsi(t_kodbar.getText())) {
                        JOptionPane.showMessageDialog(this, "Barang sudah terdaftar!");
                        bersihBarang();
                    } else {
                        servis.tambahData(smt);
                        servis_detmasuk.sumTotal(det_masuk);
                        lb_tobar.setText(det_masuk.getSubtotal_masuk().toString());
                        loadDataSementara();
                        aktif();
                        bersihBarang();
                        t_kodbar.requestFocus();

                    }

                }

            } else {
                bersihBarang();
            }
        }
    }//GEN-LAST:event_t_jumbarActionPerformed

    private void t_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subtotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean closable = true;
        Data_Barang datbar = new Data_Barang(null, closable);
        datbar.setVisible(true);

        t_kodbar.setText(datbar.brg.getKode_barang());
        t_nambar.setText(datbar.brg.getNama_barang());
        t_satuan.setText(datbar.brg.getSatuan());
        t_harbar.setText(datbar.brg.getHarga().toString());
        t_jumbar.setEditable(true);
        t_jumbar.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_noActionPerformed

    private void t_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tanggalActionPerformed

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked

    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked

    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_hapusdata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata2MouseClicked

    }//GEN-LAST:event_bt_hapusdata2MouseClicked

    private void bt_perbaruisemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_perbaruisemMouseClicked

    }//GEN-LAST:event_bt_perbaruisemMouseClicked

    private void bt_hapusemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusemMouseClicked
        hapusDataSementara();
        bersihBarang();
    }//GEN-LAST:event_bt_hapusemMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        tampilPanel();
        pn_detail.setVisible(false);
        loadData();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahBarangMasuk);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambahdata1.setText("SIMPAN");
        t_no.setText(servis_masuk.nomor());
        setTanggal();

        if (bt_tambahdata.getText().equals("UBAH")) {
            dataTabel();
            //lb_nb.setVisible(false);

        }
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_tambahdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdata1ActionPerformed
        if (bt_tambahdata1.getText().equals("TAMBAH")) {
            tambahData();
            bt_tambahdata1.setText("SIMPAN");
        } else if (bt_tambahdata1.getText().equals("SIMPAN")) {
            
            simpanData();

//            String no = t_no.getText();
//            servis_lap.lapBarangMasuk(no);
            tampilPanel();
            loadData();
            resetForm();
            loadDataSementara();

        }
    }//GEN-LAST:event_bt_tambahdata1ActionPerformed

    private void bt_hapusdata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdata2ActionPerformed
        servis.hapusIsi();
        tampilPanel();
        loadData();
        resetForm();

    }//GEN-LAST:event_bt_hapusdata2ActionPerformed

    private void bt_hapusemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusemActionPerformed

        hapusDataSementara();
        bersihBarang();
    }//GEN-LAST:event_bt_hapusemActionPerformed

    private void bt_perbaruisemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_perbaruisemActionPerformed
        if (t_jumbar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah masih kosong!");
        } else if (t_jumbar.getText().toString().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jumlah tidak boleh 0!");
        } else {
            perbaruiData();
        }
    }//GEN-LAST:event_bt_perbaruisemActionPerformed

    String kata;
    private void t_jumbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumbarKeyReleased

        char key = (char) evt.getKeyCode();
        if (key >= '0' && key <= '9' || key == '\b' || key == '\n') {
            Integer a = 0, b = 0;
            if (!(t_jumbar.getText().isEmpty())) {
                a = Integer.parseInt(t_harbar.getText());
                b = Integer.parseInt(t_jumbar.getText());
            }
            Integer x = a * b;
            t_subtotal.setText(x.toString());
            kata = t_jumbar.getText();

        } else {
            t_jumbar.setText(kata);
        }

    }//GEN-LAST:event_t_jumbarKeyReleased

    private void t_jumbarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumbarKeyTyped
        bt_hapusem.setEnabled(false);
    }//GEN-LAST:event_t_jumbarKeyTyped

    private void t_jumbarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumbarKeyPressed

    }//GEN-LAST:event_t_jumbarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_hapusdata2;
    private javax.swing.JButton bt_hapusem;
    private javax.swing.JButton bt_perbaruisem;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_tambahdata1;
    private javax.swing.JPanel dataBarangMasuk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_tobar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JTextField t_cari;
    public javax.swing.JTextField t_harbar;
    public javax.swing.JTextField t_iddis;
    public javax.swing.JTextField t_jumbar;
    public javax.swing.JTextField t_kodbar;
    public javax.swing.JTextField t_namadis;
    public javax.swing.JTextField t_nambar;
    private javax.swing.JTextField t_no;
    public javax.swing.JTextField t_satuan;
    public javax.swing.JTextField t_subtotal;
    private javax.swing.JTextField t_tanggal;
    private javax.swing.JPanel tambahBarangMasuk;
    private javax.swing.JTable tbl_BarangMasuk;
    private javax.swing.JTable tbl_detail;
    private javax.swing.JTable tbl_sementara;
    // End of variables declaration//GEN-END:variables
    private void loadData() {
        //bt_hapusdata.setVisible(false);

        List<Model_BarangMasuk> list = servis_masuk.getData();
        tblModel_masuk.setData(list);
    }

    private void pencarian() {
        List<Model_BarangMasuk> list = servis_masuk.pencarian(t_cari.getText());
        tblModel_masuk.setData(list);
    }

    private void resetForm() {
        t_no.setText("");
        t_tanggal.setText("");
        t_iddis.setText("");
        t_namadis.setText("");
        t_kodbar.setText("");
        t_nambar.setText("");
        t_satuan.setText("");
        t_harbar.setText("");
        t_jumbar.setText("");
        t_subtotal.setText("0");
        lb_tobar.setText("0");

    }

    private void nonAktif() {
        t_no.setEditable(false);
        t_iddis.setEditable(false);
        t_tanggal.setEditable(false);
        t_namadis.setEditable(false);
        t_kodbar.setEditable(false);
        t_nambar.setEditable(false);
        t_satuan.setEditable(false);
        t_harbar.setEditable(false);
        t_subtotal.setEditable(false);
    }

    private void aktif() {
    }

    private void perbaruiData() {
        int index = tbl_sementara.getSelectedRow();
        if (index != -1) {
            Model_SemBarangMasuk modsem = tblModel.getData(tbl_sementara.convertRowIndexToModel(index));

            String kode_barang = t_kodbar.getText();
            String nama_barang = t_nambar.getText();
            String satuan = t_satuan.getText();
            Long harga = Long.valueOf(t_harbar.getText());
            Integer jumlah = Integer.parseInt(t_jumbar.getText());
            Long subtotal = Long.valueOf(t_subtotal.getText());

            Model_SemBarangMasuk smt = new Model_SemBarangMasuk();
            Model_Barang brg = new Model_Barang();
            Model_DetBarangMasuk det_masuk = new Model_DetBarangMasuk();

            brg.setKode_barang(kode_barang);
            brg.setNama_barang(nama_barang);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            det_masuk.setJml_masuk(jumlah);
            det_masuk.setSubtotal_masuk(subtotal);

            smt.setMdl_barang(brg);
            smt.setMdl_detmasuk(det_masuk);

            Long total = Long.valueOf(lb_tobar.getText());

            Long a = Long.valueOf(tbl_sementara.getModel().getValueAt(index, 4).toString());
            Long b = Long.valueOf(tbl_sementara.getModel().getValueAt(index, 3).toString());

            total -= a * b;
            total += harga * Long.valueOf(jumlah.toString());
            lb_tobar.setText(total.toString());

            servis.perbaruiData(smt);
            tblModel.perbaruiData(index, smt);
            bersihBarang();
//            loadDataSementara();
            bt_perbaruisem.setEnabled(false);
            bt_hapusem.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diperbarui");
        }

    }

    private void dataTabel() {
        //dataBarangMasuk.setVisible(false);
        //tambahBarangMasuk.setVisible(true);

        int row = tbl_BarangMasuk.getSelectedRow();

        t_iddis.setEnabled(true);
        t_no.setEnabled(false);

        t_no.setText(tbl_BarangMasuk.getModel().getValueAt(row, 0).toString());
        t_iddis.setText(tbl_BarangMasuk.getModel().getValueAt(row, 1).toString());

        aktif();
        //bt_tambah.setText("PERBARUI");
        //bt_batal.setVisible(true);
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        String Id = lb_id.getText();
        mainPanel.add(new Form_BarangMasuk(Id));
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void hapusDataSementara() {
        int index = tbl_sementara.getSelectedRow();
        if (index != -1) {
            Model_SemBarangMasuk smt = tblModel.getData(tbl_sementara.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                int row = tbl_sementara.getSelectedRow();

                Long harga = Long.valueOf(t_harbar.getText());
                Long jumlah = Long.valueOf(t_jumbar.getText());
                Long total = Long.valueOf(lb_tobar.getText());
                total -= (jumlah * harga);
                lb_tobar.setText(total.toString());
                servis.hapusData(smt);
                tblModel.hapusData(index);
                bt_perbaruisem.setEnabled(false);
                bt_hapusem.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");

        }
    }

    private void tambahData() {
        String no = t_no.getText();

        Model_BarangMasuk masuk = new Model_BarangMasuk();
        masuk.setNo_masuk(no);

        t_no.setText(servis_masuk.nomor());
        setTanggal();
    }

    void setTanggal() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
        t_tanggal.setText(kal.format(sekarang));
    }

    private void loadDataSementara() {
        List<Model_SemBarangMasuk> list = servis.getData();
        tblModel.setData(list);
    }

    private void bersihBarang() {
        t_kodbar.setText("");
        t_nambar.setText("");
        t_satuan.setText("");
        t_harbar.setText("");
        t_jumbar.setText("");
        t_subtotal.setText("");
        t_jumbar.setEditable(false);
    }

    private void simpanData() {
        if (lb_tobar.getText().toString().equals("0")) {
            JOptionPane.showMessageDialog(null, "Data Kosong!");
        } else {
            String no_masuk = t_no.getText();
            String tgl_masuk = t_tanggal.getText();
            String kode = t_kodbar.getText();
            String nama = t_nambar.getText();
            String id_dis = t_iddis.getText();
            String id_peng = lb_id.getText();
            String status = "Sedang di masuk";

//        int jumlah      = Integer.parseInt(t_jumbar.getText());
//        Long subtotal   = Long.parseLong(t_subtotal.getText());
            Long total = Long.valueOf(lb_tobar.getText());
            Model_Barang brg = new Model_Barang();
            Model_Distributor dst = new Model_Distributor();
            Model_Pengguna pgn = new Model_Pengguna();
            Model_DetBarangMasuk det_masuk = new Model_DetBarangMasuk();
            Model_BarangMasuk masuk = new Model_BarangMasuk();

            // Simpan Tabel BarangMasuk
            masuk.setNo_masuk(no_masuk);
            masuk.setTgl_masuk(tgl_masuk);
            masuk.setTotal_masuk(total);
            dst.setId_distributor(id_dis);
            pgn.setId_pengguna(id_peng);

            masuk.setMdl_dis(dst);
            masuk.setMdl_peng(pgn);

            det_masuk.setMdl_masuk(masuk);
            det_masuk.setMdl_barang(brg);

            servis_masuk.tambahData(masuk);
            servis_detmasuk.tambahData(det_masuk);
            servis_detmasuk.hapusSementara(det_masuk);
            tblModel_masuk.tambahData(masuk);

        }

    }

}
