/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Design;

import Koneksi.Koneksi;
import DAO.*;
import Model.*;
import Service.*;
import TableModel.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author RavenPC
 */
public class Form_BarangKeluar extends javax.swing.JPanel {

    private Connection conn;

    private Service_BarangKeluar servis_keluar = new DAO_BarangKeluar();
    private Service_DetBarangKeluar servis_detkeluar = new DAO_DetBarangKeluar();

    private TblMod_BarangKeluar tblModel_keluar = new TblMod_BarangKeluar();
    private TblMod_DetBarangKeluar tblModel_detkeluar = new TblMod_DetBarangKeluar();

    private Service_SemBarangKeluar servis = new DAO_SemBarangKeluar();
    private TblMod_SemBarangKeluar tblModel = new TblMod_SemBarangKeluar();

//    private Service_Laporan servis_lap = new DAO_Laporan();
    public Form_BarangKeluar(String Id) {
        initComponents();
        bt_perbaruisem.setEnabled(false);
        bt_hapusem.setEnabled(false);
        conn = Koneksi.getConnection();

        //Pengaturan Tabel BarangKeluar
        tbl_keluar.setModel(tblModel_keluar);

        tbl_keluar.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbl_keluar.getTableHeader().setOpaque(false);
        tbl_keluar.getTableHeader().setBackground(new Color(0, 48, 88));
        tbl_keluar.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl_keluar.setRowHeight(27);

        //Pengaturan Tabel Sementara
        tbl_sementara.setModel(tblModel);
        tbl_sementara.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbl_sementara.getTableHeader().setOpaque(false);
        tbl_sementara.getTableHeader().setBackground(new Color(0, 48, 88));
        tbl_sementara.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl_sementara.setRowHeight(27);

        lb_id.setText(Id);
        //setLocationRelativeTo(null);
        tbl_sementara.setModel(tblModel);
        tbl_keluar.setModel(tblModel_keluar);
        tbl_detail.setModel(tblModel_detkeluar);
        loadData();
        loadDataSementara();
        //tbl_barang2.setModel(tblModel);
        //loadData();
        pn_detail.setVisible(false);
        resetForm();
        nonAktif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarangKeluar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_keluar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        t_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_detail = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        tambahBarangKeluar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_sementara = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        t_kodbar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t_nambar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t_harbar = new javax.swing.JTextField();
        t_jumbar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t_subtotal = new javax.swing.JTextField();
        t_satuan = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t_stok = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        lb_tobar = new javax.swing.JLabel();
        bt_tambahdata1 = new javax.swing.JButton();
        bt_hapusdata2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_no = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_tanggal = new javax.swing.JTextField();
        bt_perbaruisem = new javax.swing.JButton();
        bt_hapusem = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarangKeluar.setBackground(new java.awt.Color(255, 255, 255));
        dataBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataBarangKeluarMouseClicked(evt);
            }
        });

        tbl_keluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_keluarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_keluar);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Transaksi Barang Keluar");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/cari.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lb_id.setForeground(new java.awt.Color(0, 0, 102));
        lb_id.setText("lb_id");

        pn_detail.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 48, 88));
        jLabel4.setText("Detail Barang Keluar");

        jSeparator3.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_detail);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jSeparator3)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        bt_tambahdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata.setText("TAMBAH");
        bt_tambahdata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
        });
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangKeluarLayout = new javax.swing.GroupLayout(dataBarangKeluar);
        dataBarangKeluar.setLayout(dataBarangKeluarLayout);
        dataBarangKeluarLayout.setHorizontalGroup(
            dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataBarangKeluarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                        .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        dataBarangKeluarLayout.setVerticalGroup(
            dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_cari)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(dataBarangKeluar, "card2");

        tambahBarangKeluar.setBackground(new java.awt.Color(255, 255, 255));

        tbl_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sementaraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_sementara);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 116, 130)));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Kode Barang");

        t_kodbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel17.setText("Nama Barang");

        t_nambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("Harga");

        t_harbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        t_jumbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        t_jumbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_jumbarActionPerformed(evt);
            }
        });
        t_jumbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_jumbarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_jumbarKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setText("Jumlah");

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setText("Subtotal");

        t_subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));
        t_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_subtotalActionPerformed(evt);
            }
        });

        t_satuan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setText("Satuan");

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("...");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        t_stok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 88)));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setText("Stok");

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Barang");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t_stok)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(t_kodbar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(t_nambar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_satuan, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18)
                            .addComponent(t_harbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(jLabel19)
                            .addComponent(t_jumbar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(t_subtotal))))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_harbar)
                    .addComponent(t_kodbar)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nambar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_jumbar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Transaksi Barang Keluar");

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 153));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Total Keluar");

        lb_tobar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lb_tobar.setForeground(new java.awt.Color(0, 0, 102));
        lb_tobar.setText("Total");

        bt_tambahdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata1.setText("TAMBAH");
        bt_tambahdata1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
        });
        bt_tambahdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdata1ActionPerformed(evt);
            }
        });

        bt_hapusdata2.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata2.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_hapusdata2.setText("BATAL");
        bt_hapusdata2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_hapusdata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata2MouseClicked(evt);
            }
        });
        bt_hapusdata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdata2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Masuk");

        t_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_no.setBorder(null);
        t_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_noActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tanggal");

        t_tanggal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_tanggal.setBorder(null);
        t_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(t_no, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_no, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bt_perbaruisem.setBackground(new java.awt.Color(0, 0, 102));
        bt_perbaruisem.setForeground(new java.awt.Color(255, 255, 255));
        bt_perbaruisem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_perbaruisem.setText("PERBARUI");
        bt_perbaruisem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_perbaruisem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_perbaruisemMouseClicked(evt);
            }
        });
        bt_perbaruisem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_perbaruisemActionPerformed(evt);
            }
        });

        bt_hapusem.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusem.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/hapus.png"))); // NOI18N
        bt_hapusem.setText("HAPUS");
        bt_hapusem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_hapusem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusemMouseClicked(evt);
            }
        });
        bt_hapusem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahBarangKeluarLayout = new javax.swing.GroupLayout(tambahBarangKeluar);
        tambahBarangKeluar.setLayout(tambahBarangKeluarLayout);
        tambahBarangKeluarLayout.setHorizontalGroup(
            tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                        .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel5))
                                .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_hapusdata2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(lb_tobar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                                .addComponent(bt_perbaruisem, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_hapusem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        tambahBarangKeluarLayout.setVerticalGroup(
            tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapusdata2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_perbaruisem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_hapusem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tambahBarangKeluarLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(tambahBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tobar)
                    .addComponent(jLabel21))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        mainPanel.add(tambahBarangKeluar, "card2");

        add(mainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_keluarMouseClicked
        int row = tbl_keluar.getSelectedRow();
        String id = tbl_keluar.getValueAt(row, 0).toString();

        pn_detail.setVisible(true);
        List<Model_DetBarangKeluar> list = servis_detkeluar.getData(id);
        tblModel_detkeluar.setData(list);


    }//GEN-LAST:event_tbl_keluarMouseClicked

    private void t_jumbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_jumbarActionPerformed
        if (t_jumbar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah masih kosong!");
        } else if (t_jumbar.getText().toString().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jumlah tidak boleh 0!");
        } else {
            String kode = t_kodbar.getText();
            String nama = t_nambar.getText();
            String satuan = t_satuan.getText();
            
            bt_perbaruisem.setEnabled(false);
            
            
            Long harga = Long.valueOf(t_harbar.getText());
            int jumlah = Integer.parseInt(t_jumbar.getText());
            Long subtotal = harga * jumlah;
            t_subtotal.setText(Long.toString(subtotal));

            Model_Barang brg = new Model_Barang();
            Model_DetBarangKeluar det_keluar = new Model_DetBarangKeluar();
//        Model_BarangKeluar keluar = new Model_BarangKeluar();
            Model_SemBarangKeluar smt = new Model_SemBarangKeluar();

            brg.setKode_barang(kode);
            brg.setNama_barang(nama);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            det_keluar.setMdl_barang(brg);
            det_keluar.setJml_keluar(jumlah);
            det_keluar.setSubtotal_keluar(subtotal);

            smt.setMdl_barang(brg);
            smt.setMdl_detkeluar(det_keluar);

            if (servis_detkeluar.validasiStok(det_keluar)) {

                //sumSubTotal();
                if (JOptionPane.showConfirmDialog(this, "Mau Tambah Barang?",
                        "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    servis.tambahData(smt);
                    servis_detkeluar.sumTotal(det_keluar);
                    lb_tobar.setText(det_keluar.getSubtotal_keluar().toString());

                    loadDataSementara();
                    aktif();
                    bersihBarang();
                    t_kodbar.requestFocus();

                } else {
                    bersihBarang();
                    //t_bayar.setEditable(true);
                    //t_bayar.requestFocus();
                }
            } else {
                t_jumbar.requestFocus();
            }
        }
    }//GEN-LAST:event_t_jumbarActionPerformed

    private void t_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subtotalActionPerformed

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean closable = true;
        Data_Barang datbar = new Data_Barang(null, closable);
        datbar.setVisible(true);

        t_kodbar.setText(datbar.brg.getKode_barang());
        t_nambar.setText(datbar.brg.getNama_barang());
        t_satuan.setText(datbar.brg.getSatuan());
        t_harbar.setText(datbar.brg.getHarga().toString());
        t_stok.setText(datbar.brg.getStok().toString());
        t_jumbar.setEditable(true);
        t_jumbar.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbl_sementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sementaraMouseClicked
        int row = tbl_sementara.getSelectedRow();

        t_kodbar.setEditable(false);
        t_nambar.setEditable(false);
        t_satuan.setEditable(false);
        t_harbar.setEditable(false);
        t_subtotal.setEditable(false);

        t_kodbar.setText(tbl_sementara.getModel().getValueAt(row, 0).toString());
        t_nambar.setText(tbl_sementara.getModel().getValueAt(row, 1).toString());
        t_satuan.setText(tbl_sementara.getModel().getValueAt(row, 2).toString());
        t_harbar.setText(tbl_sementara.getModel().getValueAt(row, 3).toString());
        t_jumbar.setText(tbl_sementara.getModel().getValueAt(row, 4).toString());
        t_subtotal.setText(tbl_sementara.getModel().getValueAt(row, 5).toString());

        t_jumbar.setEditable(true);
        bt_perbaruisem.setEnabled(true);
        bt_hapusem.setEnabled(true);
    }//GEN-LAST:event_tbl_sementaraMouseClicked

    private void dataBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataBarangKeluarMouseClicked
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_dataBarangKeluarMouseClicked

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked

    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked

    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_hapusdata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata2MouseClicked

    }//GEN-LAST:event_bt_hapusdata2MouseClicked

    private void t_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_noActionPerformed

    private void t_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tanggalActionPerformed

    private void bt_perbaruisemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_perbaruisemMouseClicked

    }//GEN-LAST:event_bt_perbaruisemMouseClicked

    private void bt_hapusemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusemMouseClicked
        hapusDataSementara();
        bersihBarang();
    }//GEN-LAST:event_bt_hapusemMouseClicked

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahBarangKeluar);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambahdata1.setText("SIMPAN");
        t_no.setText(servis_keluar.nomor());
        setTanggal();
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        tampilPanel();
        pn_detail.setVisible(false);
        loadData();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void bt_tambahdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdata1ActionPerformed
        if (bt_tambahdata1.getText().equals("TAMBAH")) {
            tambahData();
            bt_tambahdata1.setText("SIMPAN");
        } else if (bt_tambahdata1.getText().equals("SIMPAN")) {
            simpanData();

            servis.hapusIsi();
            tampilPanel();
            resetForm();
            loadDataSementara();
        }
    }//GEN-LAST:event_bt_tambahdata1ActionPerformed

    private void bt_hapusdata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdata2ActionPerformed
        servis.hapusIsi();
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata2ActionPerformed

    String kata;
    private void t_jumbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumbarKeyReleased
        char key = (char) evt.getKeyCode();
        if (key >= '0' && key <= '9' || key == '\b' || key == '\n') {
            Integer a = 0, b = 0;
            if (!(t_jumbar.getText().isEmpty())) {
                a = Integer.parseInt(t_harbar.getText());
                b = Integer.parseInt(t_jumbar.getText());
            }
            Integer x = a * b;
            t_subtotal.setText(x.toString());
            kata = t_jumbar.getText();
        } else {
            t_jumbar.setText(kata);
        }
    }//GEN-LAST:event_t_jumbarKeyReleased

    private void bt_perbaruisemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_perbaruisemActionPerformed
        if (t_jumbar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah masih kosong!");
        } else if (t_jumbar.getText().toString().equals("0")) {
            JOptionPane.showMessageDialog(null, "Jumlah tidak boleh 0!");
        } else {
            perbaruiData();
        }
    }//GEN-LAST:event_bt_perbaruisemActionPerformed

    private void bt_hapusemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusemActionPerformed

    private void t_jumbarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_jumbarKeyTyped
        bt_hapusem.setEnabled(false);
    }//GEN-LAST:event_t_jumbarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_hapusdata2;
    private javax.swing.JButton bt_hapusem;
    private javax.swing.JButton bt_perbaruisem;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_tambahdata1;
    private javax.swing.JPanel dataBarangKeluar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_tobar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_detail;
    private javax.swing.JTextField t_cari;
    public javax.swing.JTextField t_harbar;
    public javax.swing.JTextField t_jumbar;
    public javax.swing.JTextField t_kodbar;
    public javax.swing.JTextField t_nambar;
    private javax.swing.JTextField t_no;
    public javax.swing.JTextField t_satuan;
    public javax.swing.JTextField t_stok;
    public javax.swing.JTextField t_subtotal;
    private javax.swing.JTextField t_tanggal;
    private javax.swing.JPanel tambahBarangKeluar;
    private javax.swing.JTable tbl_detail;
    private javax.swing.JTable tbl_keluar;
    private javax.swing.JTable tbl_sementara;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        //bt_hapusdata.setVisible(false);

        List<Model_BarangKeluar> list = servis_keluar.getData();
        tblModel_keluar.setData(list);
    }

    private void pencarian() {
        List<Model_BarangKeluar> list = servis_keluar.pencarian(t_cari.getText());
        tblModel_keluar.setData(list);
    }

    private void resetForm() {
        t_no.setText("");
        t_tanggal.setText("");
        t_kodbar.setText("");
        t_nambar.setText("");
        t_satuan.setText("");
        t_harbar.setText("");
        t_jumbar.setText("");
        t_subtotal.setText("");
        lb_tobar.setText("0");

    }

    private void nonAktif() {
        t_no.setEditable(false);
        t_tanggal.setEditable(false);
        t_kodbar.setEditable(false);
        t_nambar.setEditable(false);
        t_satuan.setEditable(false);
        t_stok.setEditable(false);
        t_harbar.setEditable(false);
        t_subtotal.setEditable(false);
    }

    private void aktif() {
    }

    private void perbaruiData() {
        int index = tbl_sementara.getSelectedRow();
        if (index != -1) {
            Model_SemBarangKeluar modsem = tblModel.getData(tbl_sementara.convertRowIndexToModel(index));

            String kode_barang = t_kodbar.getText();
            String nama_barang = t_nambar.getText();
            String satuan = t_satuan.getText();
            Long harga = Long.parseLong(t_harbar.getText());
            Integer jumlah = Integer.parseInt(t_jumbar.getText());
            Long subtotal = Long.parseLong(t_subtotal.getText());

            Model_SemBarangKeluar smt = new Model_SemBarangKeluar();
            Model_Barang brg = new Model_Barang();
            Model_DetBarangKeluar det_keluar = new Model_DetBarangKeluar();

            brg.setKode_barang(kode_barang);
            brg.setNama_barang(nama_barang);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            det_keluar.setJml_keluar(jumlah);
            det_keluar.setSubtotal_keluar(subtotal);

            smt.setMdl_barang(brg);
            smt.setMdl_detkeluar(det_keluar);

            Long total1 = Long.valueOf(lb_tobar.getText());

            System.out.println(tbl_sementara.getModel().getValueAt(index, 4));
            Long a = Long.valueOf(tbl_sementara.getModel().getValueAt(index, 4).toString());
            Long b = Long.valueOf(tbl_sementara.getModel().getValueAt(index, 3).toString());

            System.out.println(a);
            System.out.println(b);
            System.out.println(subtotal);
            total1 -= a * b;
            total1 += harga * Long.valueOf(jumlah.toString());
            lb_tobar.setText(total1.toString());

            servis.perbaruiData(smt);
            tblModel.perbaruiData(index, smt);
//            loadDataSementara();
            bersihBarang();
            bt_perbaruisem.setEnabled(false);
            bt_hapusem.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diperbarui");
        }

    }

    private void tampilPanel() {
        mainPanel.removeAll();
        String Id = lb_id.getText();
        mainPanel.add(new Form_BarangKeluar(Id));
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void hapusDataSementara() {
        int index = tbl_sementara.getSelectedRow();
        if (index != -1) {
            Model_SemBarangKeluar smt = tblModel.getData(tbl_sementara.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                int row = tbl_sementara.getSelectedRow();

                Long harga = Long.valueOf(t_harbar.getText());
                Long jumlah = Long.valueOf(t_jumbar.getText());
                Long total = Long.valueOf(lb_tobar.getText());
                total -= (jumlah * harga);
                lb_tobar.setText(total.toString());

                servis.hapusData(smt);
                tblModel.hapusData(index);
//                loadDataSementara();
                bt_perbaruisem.setEnabled(false);
                bt_hapusem.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");

        }
    }

    private void tambahData() {
        String no = t_no.getText();

        Model_BarangKeluar keluar = new Model_BarangKeluar();
        keluar.setNo_keluar(no);

        t_no.setText(servis_keluar.nomor());
        setTanggal();
    }

    void setTanggal() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyyy-MM-dd");
        t_tanggal.setText(kal.format(sekarang));
    }

    private void loadDataSementara() {
        List<Model_SemBarangKeluar> list = servis.getData();
        tblModel.setData(list);
    }

    private void bersihBarang() {
        t_kodbar.setText("");
        t_nambar.setText("");
        t_satuan.setText("");
        t_harbar.setText("");
        t_jumbar.setText("");
        t_stok.setText("");
        t_subtotal.setText("");
        t_jumbar.setEditable(false);
    }

    private void simpanData() {
        if (lb_tobar.getText().toString().equals("0")) {
            JOptionPane.showMessageDialog(null, "Data Kosong!");
        } else {
            String no_keluar = t_no.getText();
            String tgl_keluar = t_tanggal.getText();
            String kode = t_kodbar.getText();
            String nama = t_nambar.getText();
            String id_peng = lb_id.getText();
            Long total = Long.parseLong(lb_tobar.getText());

            Model_Barang brg = new Model_Barang();
            Model_Pengguna pgn = new Model_Pengguna();
            Model_DetBarangKeluar det_keluar = new Model_DetBarangKeluar();
            Model_BarangKeluar keluar = new Model_BarangKeluar();

            // Simpan Tabel BarangKeluar
            keluar.setNo_keluar(no_keluar);
            keluar.setTgl_keluar(tgl_keluar);
            keluar.setTotal_keluar(total);
            pgn.setId_pengguna(id_peng);

            keluar.setMdl_peng(pgn);

            // Simpan Tabel Detail Barang Keluar
            det_keluar.setMdl_keluar(keluar);
            det_keluar.setMdl_barang(brg);

            servis_keluar.tambahData(keluar);
            servis_detkeluar.tambahData(det_keluar);
            servis_detkeluar.hapusSementara(det_keluar);
            tblModel_keluar.tambahData(keluar);

        }

        //tampilPanel();
    }

}
