/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Design;

import DAO.DAO_Barang;
import Model.Model_Barang;
import Model.Model_JenisBarang;
import Service.Service_Barang;
import TableModel.TblMod_Barang;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

public class Master_Barang extends javax.swing.JPanel {

    private Service_Barang servis = new DAO_Barang();
    private TblMod_Barang tblModel = new TblMod_Barang();

    public Master_Barang() {
        initComponents();

        tbl_barang.setModel(tblModel);
        tbl_barang.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbl_barang.getTableHeader().setOpaque(false);
        tbl_barang.getTableHeader().setBackground(new Color(0, 48, 88));
        tbl_barang.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl_barang.setRowHeight(27);

        //setLocationRelativeTo(null);
        tbl_barang.setModel(tblModel);
        loadData();
        resetForm();
        nonAktif();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bt_tambahdata = new javax.swing.JButton();
        bt_hapusdata = new javax.swing.JButton();
        bt_bataldata2 = new javax.swing.JButton();
        tambahBarang = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        t_namajenisbarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_jenisbarang = new javax.swing.JTextField();
        bt_jenisbarang = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t_kodebarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_namabarang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_stok = new javax.swing.JTextField();
        cbx_satuan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bt_tambahdata1 = new javax.swing.JButton();
        bt_hapusdata1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataBarang.setBackground(new java.awt.Color(255, 255, 255));

        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_barang.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barang);

        t_cari.setBackground(new java.awt.Color(255, 255, 255));
        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setForeground(new java.awt.Color(0, 0, 0));
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/cari.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Data Barang");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        bt_tambahdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata.setText("TAMBAH");
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
        });
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });
        bt_tambahdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdataKeyPressed(evt);
            }
        });

        bt_hapusdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/hapus.png"))); // NOI18N
        bt_hapusdata.setText("HAPUS");
        bt_hapusdata.setPreferredSize(new java.awt.Dimension(116, 31));
        bt_hapusdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseClicked(evt);
            }
        });
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });

        bt_bataldata2.setBackground(new java.awt.Color(0, 0, 102));
        bt_bataldata2.setForeground(new java.awt.Color(255, 255, 255));
        bt_bataldata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_bataldata2.setText("BATAL");
        bt_bataldata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bataldata2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataBarangLayout = new javax.swing.GroupLayout(dataBarang);
        dataBarang.setLayout(dataBarangLayout);
        dataBarangLayout.setHorizontalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(dataBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataBarangLayout.setVerticalGroup(
            dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBarangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(dataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_cari)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hapusdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_bataldata2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(dataBarang, "card2");

        tambahBarang.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        t_namajenisbarang.setBackground(new java.awt.Color(255, 255, 255));
        t_namajenisbarang.setForeground(new java.awt.Color(0, 0, 0));
        t_namajenisbarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama Jenis Barang");

        t_jenisbarang.setBackground(new java.awt.Color(255, 255, 255));
        t_jenisbarang.setForeground(new java.awt.Color(0, 0, 0));
        t_jenisbarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        bt_jenisbarang.setBackground(new java.awt.Color(0, 0, 102));
        bt_jenisbarang.setForeground(new java.awt.Color(255, 255, 255));
        bt_jenisbarang.setText("...");
        bt_jenisbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_jenisbarangActionPerformed(evt);
            }
        });
        bt_jenisbarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_jenisbarangKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Kode Jenis Barang");

        t_kodebarang.setBackground(new java.awt.Color(255, 255, 255));
        t_kodebarang.setForeground(new java.awt.Color(0, 0, 0));
        t_kodebarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Kode Barang");

        t_namabarang.setBackground(new java.awt.Color(255, 255, 255));
        t_namabarang.setForeground(new java.awt.Color(0, 0, 0));
        t_namabarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namabarangActionPerformed(evt);
            }
        });
        t_namabarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_namabarangKeyPressed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Nama Barang");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Satuan");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Harga");

        t_harga.setBackground(new java.awt.Color(255, 255, 255));
        t_harga.setForeground(new java.awt.Color(0, 0, 0));
        t_harga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_harga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_hargaFocusLost(evt);
            }
        });
        t_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_hargaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_hargaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_hargaKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Stok");

        t_stok.setBackground(new java.awt.Color(255, 255, 255));
        t_stok.setForeground(new java.awt.Color(0, 0, 0));
        t_stok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_stok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_stokFocusLost(evt);
            }
        });
        t_stok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_stokKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_stokKeyReleased(evt);
            }
        });

        cbx_satuan.setBackground(new java.awt.Color(255, 255, 255));
        cbx_satuan.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        cbx_satuan.setForeground(new java.awt.Color(0, 0, 0));
        cbx_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Batang", "Kg", "Buah", "Roll", "Lembar", "Karton", "Zak", "Meter", "Kaleng", "Doss" }));
        cbx_satuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_satuanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_kodebarang)
                    .addComponent(t_harga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t_stok)
                    .addComponent(cbx_satuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_jenisbarang, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(bt_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_namajenisbarang)
                    .addComponent(t_namabarang)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 464, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_jenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namajenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Data Barang");

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        bt_tambahdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata1.setText("TAMBAH");
        bt_tambahdata1.setPreferredSize(new java.awt.Dimension(116, 31));
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
        });
        bt_tambahdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdata1ActionPerformed(evt);
            }
        });
        bt_tambahdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata1KeyPressed(evt);
            }
        });

        bt_hapusdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_hapusdata1.setText("BATAL");
        bt_hapusdata1.setPreferredSize(new java.awt.Dimension(116, 31));
        bt_hapusdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseClicked(evt);
            }
        });
        bt_hapusdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdata1ActionPerformed(evt);
            }
        });
        bt_hapusdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_hapusdata1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout tambahBarangLayout = new javax.swing.GroupLayout(tambahBarang);
        tambahBarang.setLayout(tambahBarangLayout);
        tambahBarangLayout.setHorizontalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5))
                    .addGroup(tambahBarangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tambahBarangLayout.setVerticalGroup(
            tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahBarangLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(tambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(tambahBarang, "card2");

        add(mainPanel, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void bt_hapusdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseClicked

    }//GEN-LAST:event_bt_hapusdata1MouseClicked

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked

    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void t_namabarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_namabarangKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbx_satuan.requestFocus();
        }
    }//GEN-LAST:event_t_namabarangKeyPressed

    private void t_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namabarangActionPerformed

    private void bt_jenisbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_jenisbarangActionPerformed
        boolean closable = true;
        Data_JenisBarang djb = new Data_JenisBarang(null, closable);
        djb.setVisible(true);

        t_jenisbarang.setText(djb.jb.getKode_jenis());
        t_namajenisbarang.setText(djb.jb.getNama_jenis());

        t_namabarang.requestFocus();
        aktif();

        //        String namakode,kode = "";
        //        namakode = t_namajenisbarang.getText().substring(0,3).toUpperCase();
        //        kode=kode.concat(namakode);
        //        kode=kode.concat("");
        //        t_kodebarang.setText(servis.nomor()+kode+servis.nomor2());
        //        lb_nb.setVisible(false);
    }//GEN-LAST:event_bt_jenisbarangActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed
        hapusData();

    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void bt_hapusdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseClicked

    }//GEN-LAST:event_bt_hapusdataMouseClicked

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahBarang);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambahdata1.setText("SIMPAN");
        bt_jenisbarang.setEnabled(true);
        t_kodebarang.setText(servis.nomor());

        if (bt_tambahdata.getText().equals("UBAH")) {
            dataTabel();
            //lb_nb.setVisible(false);

        }
        bt_jenisbarang.requestFocus();
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked

    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        if (bt_tambahdata.getText().equals("TAMBAH")) {
            bt_tambahdata.setText("UBAH");

        }
        bt_hapusdata.setVisible(true);
        bt_bataldata2.setVisible(true);
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void bt_tambahdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdata1ActionPerformed
        if (!(t_stok.getText().isEmpty())) {
            if (Integer.parseInt(t_stok.getText().toString()) == 0) {
                JOptionPane.showMessageDialog(null, "Stok tidak boleh 0!");
                t_stok.requestFocus();
            }
        } else {
            if (bt_tambahdata1.getText().equals("TAMBAH")) {
                bt_tambahdata1.setText("SIMPAN");
                t_kodebarang.setText(servis.nomor());

            } else if (bt_tambahdata1.getText().equals("SIMPAN")) {
                simpanData();

            } else if (bt_tambahdata1.getText().equals("PERBARUI")) {
                perbaruiData();

            }
        }

    }//GEN-LAST:event_bt_tambahdata1ActionPerformed

    private void t_hargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyTyped
//        char key = (char) evt.getKeyCode();
//        if (key < 0 || key > 9) {
//            t_harga.setText("");
//        }
    }//GEN-LAST:event_t_hargaKeyTyped

    private void t_hargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!(t_harga.getText().isEmpty())) {
                if (Integer.parseInt(t_harga.getText().toString()) == 0) {
                    JOptionPane.showMessageDialog(null, "Harga tidak boleh 0!");
                    t_harga.requestFocus();
                } else {
                    t_stok.requestFocus();
                }
            } else {
                t_stok.requestFocus();
            }

        }
    }//GEN-LAST:event_t_hargaKeyPressed
    String kata;
    private void t_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_hargaKeyReleased
        char key = (char) evt.getKeyCode();
        if (key >= '0' && key <= '9' || key == '\b' || key == '\n') {
            kata = t_harga.getText();
        } else {
            t_harga.setText(kata);
        }

    }//GEN-LAST:event_t_hargaKeyReleased

    private void cbx_satuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_satuanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_harga.requestFocus();
        }
    }//GEN-LAST:event_cbx_satuanKeyPressed
    String kata2;
    private void t_stokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_stokKeyReleased
        char key = (char) evt.getKeyCode();
        if (key >= '0' && key <= '9' || key == '\b' || key == '\n') {
            kata2 = t_stok.getText();
        } else {
            t_stok.setText(kata2);
        }
    }//GEN-LAST:event_t_stokKeyReleased

    private void t_stokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_stokKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!(t_stok.getText().isEmpty())) {
                if (Integer.parseInt(t_stok.getText().toString()) == 0) {
                    JOptionPane.showMessageDialog(null, "Stok tidak boleh 0!");
                    t_stok.requestFocus();
                } else {
                    bt_tambahdata1.requestFocus();
                }
            } else {
                bt_tambahdata1.requestFocus();
            }

        }
    }//GEN-LAST:event_t_stokKeyPressed

    private void bt_hapusdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdata1ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata1ActionPerformed

    private void bt_tambahdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (bt_tambahdata1.getText().equals("TAMBAH")) {
                bt_tambahdata1.setText("SIMPAN");
                t_kodebarang.setText(servis.nomor());

            } else if (bt_tambahdata1.getText().equals("SIMPAN")) {
                simpanData();

            } else if (bt_tambahdata1.getText().equals("PERBARUI")) {
                perbaruiData();

            }
        }
    }//GEN-LAST:event_bt_tambahdata1KeyPressed

    private void bt_hapusdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_hapusdata1KeyPressed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata1KeyPressed

    private void bt_jenisbarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_jenisbarangKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boolean closable = true;
            Data_JenisBarang djb = new Data_JenisBarang(null, closable);
            djb.setVisible(true);

            t_jenisbarang.setText(djb.jb.getKode_jenis());
            t_namajenisbarang.setText(djb.jb.getNama_jenis());

            t_namabarang.requestFocus();
            aktif();
        }
    }//GEN-LAST:event_bt_jenisbarangKeyPressed

    private void bt_tambahdataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdataKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(tambahBarang);
            mainPanel.repaint();
            mainPanel.revalidate();

            bt_tambahdata1.setText("SIMPAN");
            bt_jenisbarang.setEnabled(true);
            t_kodebarang.setText(servis.nomor());

            if (bt_tambahdata.getText().equals("UBAH")) {
                dataTabel();
                //lb_nb.setVisible(false);

            }
            bt_jenisbarang.requestFocus();
        }
    }//GEN-LAST:event_bt_tambahdataKeyPressed

    private void bt_bataldata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bataldata2ActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_bt_bataldata2ActionPerformed

    private void t_hargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_hargaFocusLost

        if (!(t_harga.getText().isEmpty())) {
            if (Integer.parseInt(t_harga.getText().toString()) == 0) {
                JOptionPane.showMessageDialog(null, "Harga tidak boleh 0!");
                t_harga.requestFocus();
            }
        }
    }//GEN-LAST:event_t_hargaFocusLost

    private void t_stokFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_stokFocusLost

    }//GEN-LAST:event_t_stokFocusLost

    private void loadData() {
        bt_hapusdata.setVisible(false);
        bt_bataldata2.setVisible(false);
        List<Model_Barang> list = servis.getData();
        tblModel.setData(list);
    }

    private void pencarian() {
        List<Model_Barang> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }

    private void resetForm() {
        bt_tambahdata1.requestFocus();
        t_kodebarang.setText("");
        t_jenisbarang.setText("");
        t_namajenisbarang.setText("");
        t_namabarang.setText("");
        cbx_satuan.setSelectedItem(0);
        t_harga.setText("");
        t_stok.setText("");
    }

    private void nonAktif() {
        t_kodebarang.setEnabled(false);
        t_jenisbarang.setEnabled(false);
        bt_jenisbarang.setEnabled(false);
        t_namajenisbarang.setEnabled(false);
        t_namabarang.setEnabled(false);
        cbx_satuan.setEnabled(false);
        t_harga.setEnabled(false);
        t_stok.setEnabled(false);
    }

    private void aktif() {
        t_namabarang.setEnabled(true);
        t_namabarang.setEnabled(true);
        cbx_satuan.setEnabled(true);
        t_harga.setEnabled(true);
        t_stok.setEnabled(true);
    }

    private void perbaruiData() {
        int index = tbl_barang.getSelectedRow();
        if (index != -1) {
            Model_Barang mobar = tblModel.getData(tbl_barang.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                String kode_barang = t_kodebarang.getText();
                String kode_jenis = t_jenisbarang.getText();
                //String nama_jenis   = t_namajenisbarang.getText();
                String nama_barang = t_namabarang.getText();
                String satuan = cbx_satuan.getSelectedItem().toString();
                Long harga = Long.parseLong(t_harga.getText());
                int stok = Integer.parseInt(t_stok.getText());

                Model_Barang brg = new Model_Barang();
                Model_JenisBarang jbr = new Model_JenisBarang();

                jbr.setKode_jenis(kode_jenis);
                //jbr.setNama_jenis(nama_jenis);
                brg.setKode_barang(kode_barang);
                brg.setNama_barang(nama_barang);
                brg.setSatuan(satuan);
                brg.setHarga(harga);
                brg.setStok(stok);

                brg.setJns_barang(jbr);

                servis.perbaruiData(brg);
                tblModel.perbaruiData(index, brg);
                loadData();
                resetForm();
                tampilPanel();

            }
        }
    }

    private void dataTabel() {
        dataBarang.setVisible(false);
        tambahBarang.setVisible(true);

        int row = tbl_barang.getSelectedRow();
        jLabel5.setText("Perbarui Data Barang");

        t_kodebarang.setEnabled(false);
        t_jenisbarang.setEnabled(false);
        t_namajenisbarang.setEnabled(false);

        t_kodebarang.setText(tbl_barang.getModel().getValueAt(row, 0).toString());
        t_jenisbarang.setText(tbl_barang.getModel().getValueAt(row, 1).toString());
        t_namajenisbarang.setText(tbl_barang.getModel().getValueAt(row, 2).toString());
        t_namabarang.setText(tbl_barang.getModel().getValueAt(row, 3).toString());
        cbx_satuan.setSelectedItem(tbl_barang.getModel().getValueAt(row, 4).toString());
        t_harga.setText(tbl_barang.getModel().getValueAt(row, 5).toString());
        t_stok.setText(tbl_barang.getModel().getValueAt(row, 6).toString());

        aktif();
        bt_tambahdata1.setText("PERBARUI");
        bt_hapusdata1.setVisible(true);
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Master_Barang());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void hapusData() {
        int index = tbl_barang.getSelectedRow();
        if (index != -1) {
            Model_Barang brg = tblModel.getData(tbl_barang.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis.hapusData(brg);
                tblModel.hapusData(index);
                loadData();
                resetForm();
                bt_tambahdata.setText("TAMBAH");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");

        }
    }

    private void simpanData() {
        if (validasiInput() == true) {
            String kode_barang = t_kodebarang.getText();
            String kode_jenis = t_jenisbarang.getText();
            String nama_jenisbarang = t_namajenisbarang.getText();
            String nama_barang = t_namabarang.getText();
            String satuan = cbx_satuan.getSelectedItem().toString();
            Long harga = Long.parseLong(t_harga.getText());
            int stok = Integer.parseInt(t_stok.getText());

            Model_Barang brg = new Model_Barang();
            Model_JenisBarang jbr = new Model_JenisBarang();

            brg.setKode_barang(kode_barang);
            jbr.setKode_jenis(kode_jenis);
            jbr.setNama_jenis(nama_jenisbarang);
            brg.setNama_barang(nama_barang);
            brg.setSatuan(satuan);
            brg.setHarga(harga);
            brg.setStok(stok);

            brg.setJns_barang(jbr);

            servis.tambahData(brg);
            tblModel.tambahData(brg);
            loadData();
            resetForm();
            tampilPanel();
            bt_tambahdata1.setText("TAMBAH");
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (t_kodebarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Barang tidak boleh kosong");
        } else if (t_jenisbarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Jenis Barang tidak boleh kosong");
        } else if (t_namajenisbarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Jenis Barang tidak boleh kosong");
        } else if (t_namabarang.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Barang tidak boleh kosong");
        } else if (cbx_satuan.getSelectedItem().equals(null)) {
            JOptionPane.showMessageDialog(null, "Satuan tidak boleh kosong");
        } else if (t_harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga tidak boleh kosong");
        } else if (t_stok.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Stok tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_bataldata2;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_hapusdata1;
    private javax.swing.JButton bt_jenisbarang;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_tambahdata1;
    private javax.swing.JComboBox<String> cbx_satuan;
    private javax.swing.JPanel dataBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_harga;
    public javax.swing.JTextField t_jenisbarang;
    private javax.swing.JTextField t_kodebarang;
    private javax.swing.JTextField t_namabarang;
    private javax.swing.JTextField t_namajenisbarang;
    private javax.swing.JTextField t_stok;
    private javax.swing.JPanel tambahBarang;
    private javax.swing.JTable tbl_barang;
    // End of variables declaration//GEN-END:variables
}
