/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Design;

import DAO.DAO_JenisBarang;
import Model.Model_JenisBarang;
import Service.Service_JenisBarang;
import TableModel.TblMod_JenisBarang;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class Master_JenisBarang extends javax.swing.JPanel {

    /**
     * Creates new form Master_JenisBarang
     */
    private Service_JenisBarang servis = new DAO_JenisBarang();
    private TblMod_JenisBarang tblModel = new TblMod_JenisBarang();
    
    public Master_JenisBarang() {
        initComponents();
        tbl_jenisbarang.setModel(tblModel);
        tbl_jenisbarang.getTableHeader().setFont(new Font ("Segoe UI", Font.BOLD, 12));
        tbl_jenisbarang.getTableHeader().setOpaque(false);
        tbl_jenisbarang.getTableHeader().setBackground(new Color(0,48,88));
        tbl_jenisbarang.getTableHeader().setForeground(new Color(255,255,255));
        tbl_jenisbarang.setRowHeight(27);
        t_kodejenis.setEditable(false);
        //setLocationRelativeTo(null);
        tbl_jenisbarang.setModel(tblModel);
        loadData();
        resetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataJenisBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jenisbarang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        t_cari = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        bt_hapusdata = new javax.swing.JButton();
        bt_bataldata2 = new javax.swing.JButton();
        tambahJenisBarang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_kodejenis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_namajenis = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        bt_tambahdata1 = new javax.swing.JButton();
        bt_hapusdata1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataJenisBarang.setBackground(new java.awt.Color(255, 255, 255));

        tbl_jenisbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_jenisbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_jenisbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_jenisbarang);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/cari.png"))); // NOI18N

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Jenis Barang");

        bt_tambahdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata.setText("TAMBAH");
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
        });
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        bt_hapusdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/hapus.png"))); // NOI18N
        bt_hapusdata.setText("HAPUS");
        bt_hapusdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseClicked(evt);
            }
        });
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });

        bt_bataldata2.setBackground(new java.awt.Color(0, 0, 102));
        bt_bataldata2.setForeground(new java.awt.Color(255, 255, 255));
        bt_bataldata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_bataldata2.setText("BATAL");
        bt_bataldata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bataldata2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataJenisBarangLayout = new javax.swing.GroupLayout(dataJenisBarang);
        dataJenisBarang.setLayout(dataJenisBarangLayout);
        dataJenisBarangLayout.setHorizontalGroup(
            dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataJenisBarangLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataJenisBarangLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataJenisBarangLayout.setVerticalGroup(
            dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_bataldata2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hapusdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_cari, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataJenisBarang, "card2");

        tambahJenisBarang.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Kode Jenis Barang");

        t_kodejenis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_kodejenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodejenisActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Nama Jenis Barang");

        t_namajenis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namajenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namajenisActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Data Jenis Barang");

        bt_tambahdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata1.setText("TAMBAH");
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
        });
        bt_tambahdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdata1ActionPerformed(evt);
            }
        });

        bt_hapusdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_hapusdata1.setText("BATAL");
        bt_hapusdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdata1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahJenisBarangLayout = new javax.swing.GroupLayout(tambahJenisBarang);
        tambahJenisBarang.setLayout(tambahJenisBarangLayout);
        tambahJenisBarangLayout.setHorizontalGroup(
            tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                        .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(541, 541, 541))
                    .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                        .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tambahJenisBarangLayout.createSequentialGroup()
                                .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(t_kodejenis)
                            .addComponent(t_namajenis)
                            .addComponent(jSeparator2))
                        .addContainerGap())))
        );
        tambahJenisBarangLayout.setVerticalGroup(
            tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahJenisBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahJenisBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_kodejenis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_namajenis, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        mainPanel.add(tambahJenisBarang, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_jenisbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_jenisbarangMouseClicked
        if(bt_tambahdata.getText().equals("TAMBAH"))
        {
            bt_tambahdata.setText("UBAH");

        }
        bt_hapusdata.setVisible(true);
        bt_bataldata2.setVisible(true);
    }//GEN-LAST:event_tbl_jenisbarangMouseClicked

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_kodejenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodejenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodejenisActionPerformed

    private void t_namajenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namajenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namajenisActionPerformed

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked
        
    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void bt_hapusdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseClicked
        
    }//GEN-LAST:event_bt_hapusdataMouseClicked

    private void bt_tambahdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdata1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_tambahdata1ActionPerformed

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked
        if(bt_tambahdata1.getText().equals("TAMBAH"))
        {
            bt_tambahdata1.setText("SIMPAN");
            t_kodejenis.setText(servis.nomor());

        }
        else if(bt_tambahdata1.getText().equals("SIMPAN"))
        {
            simpanData();

        }
        else if(bt_tambahdata1.getText().equals("PERBARUI"))
        {
            perbaruiData();

        }
    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_hapusdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdata1ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata1ActionPerformed

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahJenisBarang);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambahdata1.setText("SIMPAN");

        t_kodejenis.setText(servis.nomor());

        if(bt_tambahdata.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed
        hapusData();
    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void bt_bataldata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bataldata2ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_bataldata2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_bataldata2;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_hapusdata1;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_tambahdata1;
    private javax.swing.JPanel dataJenisBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_kodejenis;
    private javax.swing.JTextField t_namajenis;
    private javax.swing.JPanel tambahJenisBarang;
    private javax.swing.JTable tbl_jenisbarang;
    // End of variables declaration//GEN-END:variables
    private void loadData() {
        bt_hapusdata.setVisible(false);
        bt_bataldata2.setVisible(false);
        List<Model_JenisBarang> list = servis.getData();
        tblModel.setData(list);
    }

    private void pencarian() {
        List<Model_JenisBarang> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
    
    private void resetForm() {
        bt_tambahdata1.requestFocus();
        t_kodejenis.setText("");
        t_namajenis.setText("");
    }

    private void perbaruiData() {
        int index = tbl_jenisbarang.getSelectedRow();
        if (index!=-1) {
            Model_JenisBarang mokat = tblModel.getData(tbl_jenisbarang.convertRowIndexToModel(index));
             
            String kodejenis  = t_kodejenis.getText();
            String namajenis  = t_namajenis.getText();
                    
            Model_JenisBarang jb = new Model_JenisBarang();
            jb.setKode_jenis(kodejenis);
            jb.setNama_jenis(namajenis);
                
            servis.perbaruiData(jb);
            tblModel.perbaruiData(index, jb);
            loadData();
            resetForm();
            tampilPanel();
            
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diperbarui");
        }
    }

    private void hapusData() {
        int index = tbl_jenisbarang.getSelectedRow();
        if (index!=-1) {
            Model_JenisBarang jb = tblModel.getData(tbl_jenisbarang.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                servis.hapusData(jb);
                tblModel.hapusData(index);
                loadData();
                resetForm();
                bt_tambahdata.setText("TAMBAH");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");
        
        }
    }
    
    private void dataTabel(){
        dataJenisBarang.setVisible(false);
        tambahJenisBarang.setVisible(true);
        
        int row = tbl_jenisbarang.getSelectedRow();

        t_namajenis.setEnabled(true);
        t_kodejenis.setEnabled(false);

        t_kodejenis.setText   (tbl_jenisbarang.getModel().getValueAt(row, 0).toString());
        t_namajenis.setText   (tbl_jenisbarang.getModel().getValueAt(row, 1).toString());

        bt_tambahdata1.setText("PERBARUI");
        bt_hapusdata1.setVisible(true);
    }
    
    private void tampilPanel(){
        mainPanel.removeAll();
        mainPanel.add(new Master_JenisBarang());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void simpanData() {
        String kode = t_kodejenis.getText();
        String nama = t_namajenis.getText();
        
        Model_JenisBarang jb = new Model_JenisBarang();
        jb.setKode_jenis(kode);
        jb.setNama_jenis(nama);
        
        if(servis.validasiNamaJenisBarang(jb)==true)
        {
            if(validasiInput()==true){
                String kode_jenis   = t_kodejenis.getText();
                String nama_jenis = t_namajenis.getText();

                Model_JenisBarang jbg = new Model_JenisBarang();
                jbg.setKode_jenis(kode_jenis);
                jbg.setNama_jenis(nama_jenis);

                servis.tambahData(jb);
                tblModel.tambahData(jb);
                tampilPanel();
                loadData();
                resetForm();
                bt_tambahdata1.setText("TAMBAH");
            }
        }else
        {
            t_namajenis.requestFocus();
        }
    }
    
    private boolean validasiInput() {
        
            boolean valid = false;
            if (t_kodejenis.getText().trim().isEmpty() )
            {
                JOptionPane.showMessageDialog(null, "Kode Jenis Barang tidak boleh kosong");
            }else if (t_namajenis.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Nama Jenis Barang tidak boleh kosong");
            }else{
                valid = true;
            }
            return valid;
        
    }

}
