/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Design;

import DAO.DAO_Pengguna;
import Model.Model_Pengguna;
import Service.Service_Pengguna;
import TableModel.TblMod_Pengguna;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

public class Master_Pengguna extends javax.swing.JPanel {

    private Service_Pengguna servis = new DAO_Pengguna();
    private TblMod_Pengguna tblModel = new TblMod_Pengguna();

    public Master_Pengguna() {
        initComponents();

        tbl_pengguna.setModel(tblModel);
        tbl_pengguna.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tbl_pengguna.getTableHeader().setOpaque(false);
        tbl_pengguna.getTableHeader().setBackground(new Color(0, 48, 88));
        tbl_pengguna.getTableHeader().setForeground(new Color(255, 255, 255));
        tbl_pengguna.setRowHeight(27);
        t_id.setEditable(false);
        //setLocationRelativeTo(null);
        tbl_pengguna.setModel(tblModel);
        loadData();
        resetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataPengguna = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengguna = new javax.swing.JTable();
        t_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bt_tambahdata = new javax.swing.JButton();
        bt_hapusdata = new javax.swing.JButton();
        bt_bataldata2 = new javax.swing.JButton();
        tambahPengguna = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_nama = new javax.swing.JTextField();
        t_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_telepon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_alamat = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbx_level = new javax.swing.JComboBox<>();
        bt_tambahdata1 = new javax.swing.JButton();
        bt_hapusdata1 = new javax.swing.JButton();
        t_password = new javax.swing.JPasswordField();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataPengguna.setBackground(new java.awt.Color(255, 255, 255));

        tbl_pengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_penggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pengguna);

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/cari.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Pengguna");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        bt_tambahdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata.setText("TAMBAH");
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
        });
        bt_tambahdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdataActionPerformed(evt);
            }
        });

        bt_hapusdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/hapus.png"))); // NOI18N
        bt_hapusdata.setText("HAPUS");
        bt_hapusdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseClicked(evt);
            }
        });
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });

        bt_bataldata2.setBackground(new java.awt.Color(0, 0, 102));
        bt_bataldata2.setForeground(new java.awt.Color(255, 255, 255));
        bt_bataldata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_bataldata2.setText("BATAL");
        bt_bataldata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseClicked(evt);
            }
        });
        bt_bataldata2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_bataldata2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPenggunaLayout = new javax.swing.GroupLayout(dataPengguna);
        dataPengguna.setLayout(dataPenggunaLayout);
        dataPenggunaLayout.setHorizontalGroup(
            dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPenggunaLayout.createSequentialGroup()
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dataPenggunaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dataPenggunaLayout.setVerticalGroup(
            dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_bataldata2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_cari)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hapusdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataPengguna, "card2");

        tambahPengguna.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID Pengguna");

        t_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });
        t_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_idKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nama Pengguna");

        t_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });
        t_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_namaKeyPressed(evt);
            }
        });

        t_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        t_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_usernameKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Username");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Password");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Telepon");

        t_telepon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_telepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_teleponActionPerformed(evt);
            }
        });
        t_telepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_teleponKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_teleponKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Alamat");

        t_alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_alamatActionPerformed(evt);
            }
        });
        t_alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_alamatKeyPressed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Data Pengguna");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Level");

        cbx_level.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cbx_level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Staff" }));
        cbx_level.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbx_levelKeyPressed(evt);
            }
        });

        bt_tambahdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata1.setText("TAMBAH");
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
        });
        bt_tambahdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdata1ActionPerformed(evt);
            }
        });
        bt_tambahdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata1KeyPressed(evt);
            }
        });

        bt_hapusdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_hapusdata1.setText("BATAL");
        bt_hapusdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseClicked(evt);
            }
        });
        bt_hapusdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdata1ActionPerformed(evt);
            }
        });

        t_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_passwordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout tambahPenggunaLayout = new javax.swing.GroupLayout(tambahPengguna);
        tambahPengguna.setLayout(tambahPenggunaLayout);
        tambahPenggunaLayout.setHorizontalGroup(
            tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(tambahPenggunaLayout.createSequentialGroup()
                        .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahPenggunaLayout.createSequentialGroup()
                        .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_username, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_nama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_id, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_telepon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_alamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_level, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahPenggunaLayout.createSequentialGroup()
                                .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahPenggunaLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel5))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tambahPenggunaLayout.createSequentialGroup()
                                        .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                                .addGap(47, 47, 47)))
                        .addContainerGap())))
        );
        tambahPenggunaLayout.setVerticalGroup(
            tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_hapusdata1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbx_level, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahPengguna, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_penggunaMouseClicked
        if (bt_tambahdata.getText().equals("TAMBAH")) {
            bt_tambahdata.setText("UBAH");

        }
        bt_hapusdata.setVisible(true);
        bt_bataldata2.setVisible(true);
    }//GEN-LAST:event_tbl_penggunaMouseClicked

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void t_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_teleponActionPerformed

    private void t_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_alamatActionPerformed

    private void bt_tambahdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdataActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahPengguna);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambahdata1.setText("SIMPAN");

        t_id.setText(servis.nomor());

        if (bt_tambahdata.getText().equals("UBAH")) {
            
            dataTabel();
            if(t_id.getText().equals("USR2207001")) {
                cbx_level.setEnabled(false);
            } else {
                cbx_level.setEnabled(true);
            }
        }
    }//GEN-LAST:event_bt_tambahdataActionPerformed

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked
        
    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void bt_hapusdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseClicked

    }//GEN-LAST:event_bt_hapusdataMouseClicked

    private void bt_bataldata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseClicked
        
    }//GEN-LAST:event_bt_bataldata2MouseClicked

    private void bt_tambahdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdata1ActionPerformed
        if (bt_tambahdata1.getText().equals("TAMBAH")) {
            bt_tambahdata1.setText("SIMPAN");
            t_id.setText(servis.nomor());

        } else if (bt_tambahdata1.getText().equals("SIMPAN")) {
            simpanData();

        } else if (bt_tambahdata1.getText().equals("PERBARUI")) {
            perbaruiData();

        }
    }//GEN-LAST:event_bt_tambahdata1ActionPerformed

    private void bt_hapusdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdata1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_hapusdata1ActionPerformed

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked
        
    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_hapusdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseClicked
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata1MouseClicked

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed
        hapusData();
    }//GEN-LAST:event_bt_hapusdataActionPerformed

    private void bt_bataldata2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_bataldata2ActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_bt_bataldata2ActionPerformed
    String kata;
    private void t_teleponKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_teleponKeyReleased
        char key = (char) evt.getKeyCode();
        if (key >= '0' && key <= '9' || key == '\b' || key=='\n') {
            kata = t_telepon.getText();
        } else {
            t_telepon.setText(kata);
        }
    }//GEN-LAST:event_t_teleponKeyReleased

    private void cbx_levelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbx_levelKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bt_tambahdata1.requestFocus();
        }
    }//GEN-LAST:event_cbx_levelKeyPressed

    private void t_alamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_alamatKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cbx_level.requestFocus();
        }
    }//GEN-LAST:event_t_alamatKeyPressed

    private void t_teleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_teleponKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_alamat.requestFocus();
        }
    }//GEN-LAST:event_t_teleponKeyPressed

    private void t_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_passwordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_telepon.requestFocus();
        }
    }//GEN-LAST:event_t_passwordKeyPressed

    private void t_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_usernameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_password.requestFocus();
        }
    }//GEN-LAST:event_t_usernameKeyPressed

    private void t_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_namaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_username.requestFocus();
        }
    }//GEN-LAST:event_t_namaKeyPressed

    private void t_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_idKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            t_nama.requestFocus();
        }
    }//GEN-LAST:event_t_idKeyPressed

    private void bt_tambahdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (bt_tambahdata1.getText().equals("TAMBAH")) {
            bt_tambahdata1.setText("SIMPAN");
            t_id.setText(servis.nomor());

        } else if (bt_tambahdata1.getText().equals("SIMPAN")) {
            simpanData();

        } else if (bt_tambahdata1.getText().equals("PERBARUI")) {
            perbaruiData();

        }
        }
    }//GEN-LAST:event_bt_tambahdata1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_bataldata2;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_hapusdata1;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_tambahdata1;
    private javax.swing.JComboBox<String> cbx_level;
    private javax.swing.JPanel dataPengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_alamat;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nama;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_telepon;
    private javax.swing.JTextField t_username;
    private javax.swing.JPanel tambahPengguna;
    private javax.swing.JTable tbl_pengguna;
    // End of variables declaration//GEN-END:variables
private void loadData() {
        bt_hapusdata.setVisible(false);
        bt_bataldata2.setVisible(false);
        List<Model_Pengguna> list = servis.getData();
        tblModel.setData(list);
    }

    private void pencarian() {
        List<Model_Pengguna> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }

    private void resetForm() {
        bt_tambahdata1.requestFocus();
        t_id.setText("");
        t_nama.setText("");
    }

    private void nonAktif() {

    }

    private void perbaruiData() {
        int index = tbl_pengguna.getSelectedRow();
        if (index != -1) {
            Model_Pengguna modis = tblModel.getData(tbl_pengguna.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                String id = t_id.getText();
                String nama = t_nama.getText();
                String username = t_username.getText();
                //String password   = t_password.getText();
                String telepon = t_telepon.getText();
                String alamat = t_alamat.getText();
                String level = cbx_level.getSelectedItem().toString();

                Model_Pengguna pgn = new Model_Pengguna();
                pgn.setId_pengguna(id);
                pgn.setNama_pengguna(nama);
                pgn.setUsername(username);
                //pgn.setPassword         (password);
                pgn.setTelp_pengguna(telepon);
                pgn.setAlamat_pengguna(alamat);
                pgn.setLevel(level);

                servis.perbaruiData(pgn);
                tblModel.perbaruiData(index, pgn);
                loadData();
                resetForm();
                tampilPanel();
            }
        }
    }

    private void hapusData() {
        int index = tbl_pengguna.getSelectedRow();
        if (index != -1) {
            if (index == 0) {
                JOptionPane.showMessageDialog(null, "Ini adalah akun Owner Utama, tidak bisa dihapus");
            } else {
                Model_Pengguna pgn = tblModel.getData(tbl_pengguna.convertRowIndexToModel(index));
                if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                    servis.hapusData(pgn);
                    tblModel.hapusData(index);

                }
            }
            loadData();
            resetForm();
            bt_tambahdata.setText("TAMBAH");

        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");

        }
    }

    private void dataTabel() {
        dataPengguna.setVisible(false);
        tambahPengguna.setVisible(true);

        int row = tbl_pengguna.getSelectedRow();

        t_nama.setEnabled(true);
        t_id.setEnabled(false);

        t_id.setText(tbl_pengguna.getModel().getValueAt(row, 0).toString());
        t_nama.setText(tbl_pengguna.getModel().getValueAt(row, 1).toString());
        t_username.setText(tbl_pengguna.getModel().getValueAt(row, 2).toString());
        //t_password.setText  (tbl_pengguna.getModel().getValueAt(row, 3).toString());
        t_telepon.setText(tbl_pengguna.getModel().getValueAt(row, 3).toString());
        t_alamat.setText(tbl_pengguna.getModel().getValueAt(row, 4).toString());
        cbx_level.setSelectedItem(tbl_pengguna.getModel().getValueAt(row, 5).toString());

        jLabel9.setVisible(false);
        t_password.setVisible(false);
        bt_tambahdata1.setText("PERBARUI");
        bt_hapusdata1.setVisible(true);
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new Master_Pengguna());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void simpanData() {
        if (validasiInput() == true) {
            String id = t_id.getText();
            String nama = t_nama.getText();
            String username = t_username.getText();
            String password = t_password.getText();
            String telepon = t_telepon.getText();
            String alamat = t_alamat.getText();
            String level = cbx_level.getSelectedItem().toString();

            Model_Pengguna pgn = new Model_Pengguna();
            pgn.setId_pengguna(id);
            pgn.setNama_pengguna(nama);
            pgn.setUsername(username);
            pgn.setPassword(password);
            pgn.setTelp_pengguna(telepon);
            pgn.setAlamat_pengguna(alamat);
            pgn.setLevel(level);

            servis.tambahData(pgn);
            tblModel.tambahData(pgn);
            tampilPanel();
            loadData();
            resetForm();
            bt_tambahdata1.setText("TAMBAH");
        }
    }

    private boolean validasiInput() {
        boolean valid = false;
        if (t_id.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Pengguna tidak boleh kosong");
        } else if (t_nama.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Pengguna tidak boleh kosong");
        } else if (t_username.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
        } else if (t_password.getText().trim().isEmpty() && !(bt_tambahdata1.getText().equals("PERBARUI"))) {
            JOptionPane.showMessageDialog(null, "Password tidak boleh kosong");
        } else if (t_telepon.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Telepon tidak boleh kosong");
        }else if (t_telepon.getText().length()<10 ){
            JOptionPane.showMessageDialog(null, "No Telepon terlalu pendek");
        }else if (t_telepon.getText().length()>13 ){
            JOptionPane.showMessageDialog(null, "No Telepon terlalu panjang");
        } else if (t_alamat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong");
        } else if (cbx_level.getSelectedItem().equals("- Pilih Akses Level -")) {
            JOptionPane.showMessageDialog(null, "Level tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }
}
