/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Design;

import DAO.DAO_Distributor;
import Model.Model_Distributor;
import Service.Service_Distributor;
import TableModel.TblMod_Distributor;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

public class Master_Distributor extends javax.swing.JPanel {

    private Service_Distributor servis = new DAO_Distributor();
    private TblMod_Distributor tblModel = new TblMod_Distributor();
    
    public Master_Distributor() {
        initComponents();
        tbl_distributor.setModel(tblModel);
        tbl_distributor.getTableHeader().setFont(new Font ("Segoe UI", Font.BOLD, 12));
        tbl_distributor.getTableHeader().setOpaque(false);
        tbl_distributor.getTableHeader().setBackground(new Color(0,48,88));
        tbl_distributor.getTableHeader().setForeground(new Color(255,255,255));
        tbl_distributor.setRowHeight(27);
        t_iddistributor.setEditable(false);
        //setLocationRelativeTo(null);
        tbl_distributor.setModel(tblModel);
        loadData();
        resetForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataDistributor = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_distributor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        t_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_tambahdata = new javax.swing.JButton();
        bt_hapusdata = new javax.swing.JButton();
        bt_bataldata2 = new javax.swing.JButton();
        tambahDistributor = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        t_iddistributor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_namadistributor = new javax.swing.JTextField();
        t_telpdistributor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_alamatdistributor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        bt_tambahdata1 = new javax.swing.JButton();
        bt_hapusdata1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        dataDistributor.setBackground(new java.awt.Color(255, 255, 255));

        tbl_distributor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tbl_distributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_distributorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_distributor);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 48, 88));
        jLabel1.setText("Data Distributor");

        jSeparator1.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        t_cari.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        t_cari.setText("     Pencarian");
        t_cari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(18, 61, 70)));
        t_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_cariMouseClicked(evt);
            }
        });
        t_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cariActionPerformed(evt);
            }
        });
        t_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cariKeyTyped(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/cari.png"))); // NOI18N

        bt_tambahdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata.setText("TAMBAH");
        bt_tambahdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdataMouseClicked(evt);
            }
        });

        bt_hapusdata.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/hapus.png"))); // NOI18N
        bt_hapusdata.setText("HAPUS");
        bt_hapusdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdataMouseClicked(evt);
            }
        });
        bt_hapusdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdataActionPerformed(evt);
            }
        });

        bt_bataldata2.setBackground(new java.awt.Color(0, 0, 102));
        bt_bataldata2.setForeground(new java.awt.Color(255, 255, 255));
        bt_bataldata2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_bataldata2.setText("BATAL");
        bt_bataldata2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_bataldata2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dataDistributorLayout = new javax.swing.GroupLayout(dataDistributor);
        dataDistributor.setLayout(dataDistributorLayout);
        dataDistributorLayout.setHorizontalGroup(
            dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(dataDistributorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataDistributorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(bt_tambahdata, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_hapusdata, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_bataldata2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dataDistributorLayout.setVerticalGroup(
            dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_bataldata2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_cari)
                    .addComponent(bt_hapusdata, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_tambahdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataDistributor, "card2");

        tambahDistributor.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID Distributor");

        t_iddistributor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_iddistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_iddistributorActionPerformed(evt);
            }
        });
        t_iddistributor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_iddistributorKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nama Distributor");

        t_namadistributor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_namadistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namadistributorActionPerformed(evt);
            }
        });
        t_namadistributor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_namadistributorKeyPressed(evt);
            }
        });

        t_telpdistributor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_telpdistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_telpdistributorActionPerformed(evt);
            }
        });
        t_telpdistributor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_telpdistributorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_telpdistributorKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telepon Distributor");

        t_alamatdistributor.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        t_alamatdistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_alamatdistributorActionPerformed(evt);
            }
        });
        t_alamatdistributor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_alamatdistributorKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Alamat Distributor");

        jSeparator2.setForeground(new java.awt.Color(0, 48, 88));
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 48, 88));
        jLabel5.setText("Tambah Data Distributor");

        bt_tambahdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_tambahdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_tambahdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/tambah.png"))); // NOI18N
        bt_tambahdata1.setText("TAMBAH");
        bt_tambahdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_tambahdata1MouseClicked(evt);
            }
        });
        bt_tambahdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_tambahdata1ActionPerformed(evt);
            }
        });
        bt_tambahdata1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_tambahdata1KeyPressed(evt);
            }
        });

        bt_hapusdata1.setBackground(new java.awt.Color(0, 0, 102));
        bt_hapusdata1.setForeground(new java.awt.Color(255, 255, 255));
        bt_hapusdata1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bahan/batal.png"))); // NOI18N
        bt_hapusdata1.setText("BATAL");
        bt_hapusdata1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_hapusdata1MouseClicked(evt);
            }
        });
        bt_hapusdata1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusdata1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tambahDistributorLayout = new javax.swing.GroupLayout(tambahDistributor);
        tambahDistributor.setLayout(tambahDistributorLayout);
        tambahDistributorLayout.setHorizontalGroup(
            tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_iddistributor)
                    .addComponent(t_namadistributor)
                    .addComponent(t_telpdistributor)
                    .addComponent(t_alamatdistributor)
                    .addComponent(jSeparator2)
                    .addGroup(tambahDistributorLayout.createSequentialGroup()
                        .addGroup(tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(tambahDistributorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addGroup(tambahDistributorLayout.createSequentialGroup()
                                .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_hapusdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 344, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahDistributorLayout.setVerticalGroup(
            tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDistributorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tambahDistributorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_hapusdata1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_tambahdata1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_iddistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_namadistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_telpdistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_alamatdistributor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(tambahDistributor, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_distributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_distributorMouseClicked
        if(bt_tambahdata.getText().equals("TAMBAH"))
        {
            bt_tambahdata.setText("UBAH");

        }
        bt_hapusdata.setVisible(true);
        bt_bataldata2.setVisible(true);
    }//GEN-LAST:event_tbl_distributorMouseClicked

    private void t_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_cariMouseClicked
        t_cari.setText("");
    }//GEN-LAST:event_t_cariMouseClicked

    private void t_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_cariActionPerformed

    private void t_cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cariKeyTyped
        pencarian();
    }//GEN-LAST:event_t_cariKeyTyped

    private void t_iddistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_iddistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_iddistributorActionPerformed

    private void t_namadistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namadistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namadistributorActionPerformed

    private void t_telpdistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_telpdistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_telpdistributorActionPerformed

    private void t_alamatdistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_alamatdistributorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_alamatdistributorActionPerformed

    private void bt_hapusdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdata1MouseClicked
        
    }//GEN-LAST:event_bt_hapusdata1MouseClicked

    private void bt_tambahdata1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdata1MouseClicked
        
    }//GEN-LAST:event_bt_tambahdata1MouseClicked

    private void bt_tambahdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_tambahdataMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(tambahDistributor);
        mainPanel.repaint();
        mainPanel.revalidate();

        bt_tambahdata1.setText("SIMPAN");
        
        t_iddistributor.setText(servis.nomor());

        if(bt_tambahdata.getText().equals("UBAH"))
        {
            dataTabel();
        }
    }//GEN-LAST:event_bt_tambahdataMouseClicked

    private void bt_hapusdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_hapusdataMouseClicked
        
    }//GEN-LAST:event_bt_hapusdataMouseClicked

    private void bt_bataldata2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_bataldata2MouseClicked
        tampilPanel();
        loadData();
    }//GEN-LAST:event_bt_bataldata2MouseClicked

    private void bt_hapusdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdata1ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_bt_hapusdata1ActionPerformed

    private void bt_hapusdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusdataActionPerformed
        hapusData();
    }//GEN-LAST:event_bt_hapusdataActionPerformed
    String kata;
    private void t_telpdistributorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_telpdistributorKeyReleased
        char key = (char) evt.getKeyCode();
        if (key >= '0' && key <= '9' || key == '\b' || key=='\n') {
            kata = t_telpdistributor.getText();
        } else {
            t_telpdistributor.setText(kata);
        }
    }//GEN-LAST:event_t_telpdistributorKeyReleased

    private void t_telpdistributorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_telpdistributorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            t_alamatdistributor.requestFocus();
        }
    }//GEN-LAST:event_t_telpdistributorKeyPressed

    private void t_namadistributorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_namadistributorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            t_telpdistributor.requestFocus();
        }
    }//GEN-LAST:event_t_namadistributorKeyPressed

    private void t_iddistributorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_iddistributorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            t_namadistributor.requestFocus();
        }
    }//GEN-LAST:event_t_iddistributorKeyPressed

    private void t_alamatdistributorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_alamatdistributorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            bt_tambahdata1.requestFocus();
        }
    }//GEN-LAST:event_t_alamatdistributorKeyPressed

    private void bt_tambahdata1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_tambahdata1ActionPerformed
        if(bt_tambahdata1.getText().equals("TAMBAH"))
        {
            bt_tambahdata1.setText("SIMPAN");
            t_iddistributor.setText(servis.nomor());

        }
        else if(bt_tambahdata1.getText().equals("SIMPAN"))
        {
            simpanData();

        }
        else if(bt_tambahdata1.getText().equals("PERBARUI"))
        {
            perbaruiData();
            tampilPanel();

        }
    }//GEN-LAST:event_bt_tambahdata1ActionPerformed

    private void bt_tambahdata1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_tambahdata1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if(bt_tambahdata1.getText().equals("TAMBAH"))
        {
            bt_tambahdata1.setText("SIMPAN");
            t_iddistributor.setText(servis.nomor());

        }
        else if(bt_tambahdata1.getText().equals("SIMPAN"))
        {
            simpanData();

        }
        else if(bt_tambahdata1.getText().equals("PERBARUI"))
        {
            perbaruiData();
            tampilPanel();

        }
        }
    }//GEN-LAST:event_bt_tambahdata1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_bataldata2;
    private javax.swing.JButton bt_hapusdata;
    private javax.swing.JButton bt_hapusdata1;
    private javax.swing.JButton bt_tambahdata;
    private javax.swing.JButton bt_tambahdata1;
    private javax.swing.JPanel dataDistributor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField t_alamatdistributor;
    private javax.swing.JTextField t_cari;
    private javax.swing.JTextField t_iddistributor;
    private javax.swing.JTextField t_namadistributor;
    private javax.swing.JTextField t_telpdistributor;
    private javax.swing.JPanel tambahDistributor;
    private javax.swing.JTable tbl_distributor;
    // End of variables declaration//GEN-END:variables
    private void loadData() {
        bt_hapusdata.setVisible(false);
        bt_bataldata2.setVisible(false);
        List<Model_Distributor> list = servis.getData();
        tblModel.setData(list);
    }

    private void pencarian() {
        List<Model_Distributor> list = servis.pencarian(t_cari.getText());
        tblModel.setData(list);
    }
    
    private void resetForm() {
        bt_tambahdata1.requestFocus();
        t_iddistributor.setText("");
        t_namadistributor.setText("");
        t_telpdistributor.setText("");
        t_alamatdistributor.setText("");
    }
    
    private void nonAktif(){
        
    }

    private void perbaruiData() {
        int index = tbl_distributor.getSelectedRow();
        if (index!=-1) {
            Model_Distributor modis = tblModel.getData(tbl_distributor.convertRowIndexToModel(index));
             
            if(validasiInput()==true){
            String id_distributor     = t_iddistributor.getText();
            String nama_distributor   = t_namadistributor.getText();
            String telp_distributor   = t_telpdistributor.getText();
            String alamat_distributor = t_alamatdistributor.getText();

            Model_Distributor dst = new Model_Distributor();
            dst.setId_distributor       (id_distributor);
            dst.setNama_distributor     (nama_distributor);
            dst.setTelp_distributor     (telp_distributor);
            dst.setAlamat_distributor   (alamat_distributor);
                
            servis.perbaruiData(dst);
            tblModel.perbaruiData(index, dst);
            loadData();
            resetForm();
            
            }
        }
    }

    private void hapusData() {
        int index = tbl_distributor.getSelectedRow();
        if (index!=-1) {
            Model_Distributor dst = tblModel.getData(tbl_distributor.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?","Konfirmasi", JOptionPane.OK_CANCEL_OPTION)== JOptionPane.OK_OPTION) {
                servis.hapusData(dst);
                tblModel.hapusData(index);
                loadData();
                resetForm();
                bt_tambahdata.setText("TAMBAH");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan diupdate");
        
        }
    }
    
    private void dataTabel(){
        dataDistributor.setVisible(false);
        tambahDistributor.setVisible(true);
        
        int row = tbl_distributor.getSelectedRow();
        jLabel5.setText("Perbarui Data Distributor");

        t_namadistributor.setEnabled(true);
        t_iddistributor.setEnabled(false);

        t_iddistributor.setText     (tbl_distributor.getModel().getValueAt(row, 0).toString());
        t_namadistributor.setText   (tbl_distributor.getModel().getValueAt(row, 1).toString());
        t_telpdistributor.setText   (tbl_distributor.getModel().getValueAt(row, 2).toString());
        t_alamatdistributor.setText (tbl_distributor.getModel().getValueAt(row, 3).toString());

        bt_tambahdata1.setText("PERBARUI");
        bt_hapusdata1.setVisible(true);
    }
    
    private void tampilPanel(){
        mainPanel.removeAll();
        mainPanel.add(new Master_Distributor());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void simpanData() {
        if(validasiInput()==true){
            String id_distributor     = t_iddistributor.getText();
            String nama_distributor   = t_namadistributor.getText();
            String telp_distributor   = t_telpdistributor.getText();
            String alamat_distributor = t_alamatdistributor.getText();

            Model_Distributor dst = new Model_Distributor();
            dst.setId_distributor       (id_distributor);
            dst.setNama_distributor     (nama_distributor);
            dst.setTelp_distributor     (telp_distributor);
            dst.setAlamat_distributor   (alamat_distributor);

            servis.tambahData(dst);
            tblModel.tambahData(dst);
            bt_tambahdata1.setText("TAMBAH");
            loadData();
            resetForm();
            tampilPanel();
        }    
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if (t_iddistributor.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "ID Distributor tidak boleh kosong");
        }else if (t_namadistributor.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Nama Distributor tidak boleh kosong");
        }else if (t_telpdistributor.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "No Telepon tidak boleh kosong");
        }else if (t_telpdistributor.getText().length()<10 ){
            JOptionPane.showMessageDialog(null, "No Telepon terlalu pendek");
        }else if (t_telpdistributor.getText().length()>13 ){
            JOptionPane.showMessageDialog(null, "No Telepon terlalu panjang");
        }else if (t_alamatdistributor.getText().trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong");
        }else{
            valid = true;
        }
        return valid;
    }

}
